### ISSUE TITLE
Set k8s built-in labels through the CCM

### ISSUE THREAD

**Issue by enkelprifti98** [packethost/packet-ccm#73]
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

We should be setting some of those built-in labels like `node.kubernetes.io/instance-type` and `topology.kubernetes.io/zone` so that they match with packet naming.

**Comment by deitch** [comment]
Turns out we already did. Here is output from one node:

```yaml
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    packet.com/node.asn: "65000"
    packet.com/peer.asns: "65530"
    packet.com/peer.ips: 10.99.0.2
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-09-03T14:04:10Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: baremetal_0
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: ewr1
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: master-01
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
    node.kubernetes.io/instance-type: baremetal_0
    topology.kubernetes.io/region: ewr1
```

The last two lines are the ones we need. The region is correct, but the instance-type is wrong. PR coming shortly.
